services:
  - type: web
    name: pm-intern
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 3 -k gthread -t 120 -b 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: LOG_LEVEL
        value: INFO
      # MongoDB Atlas connection string; set in Render dashboard or here if non-secret
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: internship_recommender
      - key: DISABLE_JSON_FALLBACK
        value: "True"
      # Security keys (set in Render dashboard)
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      # CORS origins for your frontend URL(s), comma-separated
      - key: CORS_ORIGINS
        value: "https://your-frontend.example.com,https://pm-intern.onrender.com"
      # Session cookie settings (if serving frontend on different domain use None + Secure)
      - key: SESSION_COOKIE_SAMESITE
        value: Lax
      - key: SESSION_COOKIE_SECURE
        value: "True"
